### ISSUE TITLE
use without auth login?

### ISSUE THREAD

**Issue by Jarrodsz** [dev-xo/stripe-stack#11]
Great template so it seems.

Just curious if one could use it without Social Auth.
How about using your own "local" Auth?

Would it be possible, for testing purposes, to use proved a user object and disable the social auth solutions?

The above is the only thing I miss on this starter would love to testdrive it and implement with my own local auth.

**Comment by dev-xo** [comment]
Hello @Jarrodsz yeah I understand your point, and it's a great one, specially for local testing.

When first I created the template, I taught social auth is something we all know already and it's kinda easy to use for production. Recently a few people told me about email / password auth implementation and i've been thinking about it.

Would you like to see "Magic Link" implementation? Or still thinking email / auth will be better for testing?
Let me know.
