### ISSUE TITLE
[ Fix ] remix.init failed due to ERR_REQUIRE_ESM for inquirer.

### ISSUE THREAD

**Issue by samjohnduke** [dev-xo/stripe-stack#150]
Ran into this problem installing the stack today. 

`Error [ERR_REQUIRE_ESM]: require() of ES Module /~/remix.init/node_modules/inquirer/lib/inquirer.js from /~/remix.init/index.js not supported.`

After a little googling i found that i had to drop the version of inquirer to 8.2.4 in order to get the CJS version and it worked fine.

**Comment by dev-xo** [comment]
Thanks for noticing, @samjohnduke! The Stack is currently undergoing a full [rework](https://github.com/dev-xo/stripe-stack/issues/109), but we've decided to update it to Remix `v2.0.0` in the meantime, until the release.

Again, thanks for noticing!

**Comment by dev-xo** [comment]
[Downgraded](https://github.com/dev-xo/stripe-stack/commit/d5397291bcd9b26bd23c4c3d99ad71197d26f1ef) to inquirer to `v8.2.4` @samjohnduke!

Notice me if this fixed the issue.

**Comment by dev-xo** [comment]
Closing for now, feel free to reopen if required!
Thanks for noticing, @samjohnduke!
