### ISSUE TITLE
Getting `Invalid `db.user.findUnique()` trying to register new account after all the setup

### ISSUE THREAD

**Issue by nikitavoloboev** [dev-xo/stripe-stack#23]
I ran `npx create-remix@latest --template dev-xo/stripe-stack`. Followed instructions. Then ran `npm run dev`.

Tried to create account but always get this error.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/6391776/199630581-9b79a983-c9df-4df5-a535-47fa10d36785.png">

Not sure what goes wrong.

I tried to run `npm run setup` manually but get this error.

```
npm run setup

> setup
> run-s setup:db setup:seed


> setup:db
> prisma generate && prisma migrate deploy

Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.5.0 | library) to ./node_modules/@prisma/client in 32ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "data.db" at "file:./data.db?connection_limit=1"

1 migration found in prisma/migrations

Error: P3005

The database schema is not empty. Read more about how to baseline an existing production database: https://pris.ly/d/migrate-baseline

ERROR: "setup:db" exited with 1.
```

I chose SQLite as DB choice.

Thanks for making the template.

**Comment by dev-xo** [comment]
Hello @nikitavoloboev ! Thanks for reaching on here.
I ran into that error before, and if im not wrong, someone else did it also.

Seems to be a migrations problem.
Try this few things and tell me how it goes:

- Cleanup ur localhost cache, and give it a new try.
- Delete `/migrations` folder inside prisma and run: `npx prisma migrate dev --name init`

Should fix it. Gonna look more into it, notice me how it goes.

**Comment by nikitavoloboev** [comment]
Deleted migrations and ran `npx prisma ..` all well there.

I did use `npm i` and `npm run dev` but tried to do it with `pnpm` as that's preferred for me but get:

```
pnpm i
node:internal/modules/cjs/loader:958
  throw err;
  ^

Error: Cannot find module '/opt/homebrew/Cellar/node/18.0.0/pnpm-global/5/node_modules/pnpm/bin/pnpm.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.9.0
```

I tried `npm i` and `npm run dev`  worked though 🎊 

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/6391776/199770331-8280e859-6f00-4796-8791-c418050eb1c1.png">

Excited to dive into the code.

**Comment by nikitavoloboev** [comment]
Will leave the issue open as it didn't work out of the box for me. I assume I am not alone in this too.

**Comment by dev-xo** [comment]
Issue gonna be closed @nikitavoloboev.
All good then?

As I know `pnpm` has issues with Prisma. 
Have a search on google about it in case you wanna know more.

**Comment by nikitavoloboev** [comment]
Yes can close issue. I can try debug the issue with pnpm myself. Thanks ag/n.
