### ISSUE TITLE
Provide option for 'one time payment' via Stripe

### ISSUE THREAD

**Issue by nikitavoloboev** [dev-xo/stripe-stack#24]
I am trying to adapt the Stripe code so instead of subscriptions, it is a one time price. I then can get a token back from Stripe for successful payment to my backend.

However if I try to setup a non subscription product in Stripe dashboard and then do all changes as per readme.md, in the end I get this error:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/6391776/199778064-0a9a2ea2-3d64-4692-a7e0-29cafb300d35.png">

When I try to actually do the purchase. Pressing `Get Basic` button here:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/6391776/199778152-73abb2c1-7063-4ea5-b7b6-58c6e2b72dd2.png">

Would love some help trying to get this working. Ideally this could be part of the template setup too. ♥️

**Comment by dev-xo** [comment]
Hello @nikitavoloboev.
Have you checked [Stripe Docs?](https://stripe.com/docs) about one time payments?

Template has been developed with Subscriptions in mind. Today I'm kinda bussy, but gonna look for it tomorrow.

Should be easy to implement, but for sure you will have to update the ` /webhook` API code.
Share with me some of the code changes you made if you want.

**Comment by nikitavoloboev** [comment]
Going to check the docs, I read through some of them and was still confused, then found this stack and got excited but it uses recurring payments.

If you want to pair on this together perhaps, I'd be happy too. Can pm on Discord or similar. :)

**Comment by dev-xo** [comment]
Gonna look into it and send you a few examples.
The implementations should be kinda easy, usually the Docs got us covered.

I'm in the Remix discord server as: XO#9732 in case you wanna add me.
