### ISSUE TITLE
/login 404

### ISSUE THREAD

**Issue by codingforfoodllc** [dev-xo/stripe-stack#49]
When I browse to 'http://localhost:3000/login' I get a 404 not found.

Steps to reproduce:
1.  Fresh install of the repo via npx create-remix@latest --template dev-xo/stripe-stack.
2.  After install is complete, run npm run start.
3.  Browse to http://localhost:3000/login

**Comment by dev-xo** [comment]
Hello @codingforfoodllc .
Gonna check it right now.

What was the dabase your project runs on?
The template is deployed on [Fly.io](https://stripe-stack.fly.dev/login) and seems to work properly on there.

Gonna look more into it, if you got some extra detail, feel free to share.

**Comment by dev-xo** [comment]
Im on Remix Discord as dev-xo#9732

Reach me on there for personal help, maybe we can fix this issue right now.

**Comment by dev-xo** [comment]
Gonna close this for now @codingforfoodllc.
I have noticed @kiliman on discord about this Issue and the talk we had.
