### ISSUE TITLE
Can't run locally with postgres

### ISSUE THREAD

**Issue by sfirrin** [dev-xo/stripe-stack#51]
Hi,

First of all thanks a lot for creating this project, I am looking forward to trying it out. 

I have created a project using `npx create-remix@latest --template dev-xo/stripe-stack` and selecting the Postgres option and I'm having trouble getting postgres to work how it should. When I go into the dir and run `npm run dev` and load localhost:3000 I get this output:

```

/Users/swf/projects/remix-stripe-2/node_modules/@prisma/client/runtime/index.js:27740
          throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);
                ^
Error: error: Error validating datasource `db`: the URL must start with the protocol `file:`.
  -->  schema.prisma:10
   |
 9 |   provider = "sqlite"
10 |   url      = env("DATABASE_URL")
   |
```

This seems like a bug because I chose postgres in the install dialog and my schema.prisma says "postgresql" instead of "sqlite". Deleting node_modules and then running `npm install` again, this seems to fix this issue, but then I get another error:

```
Remix App Server started at http://localhost:3000 (http://192.168.1.235:3000)

/Users/swf/projects/remix-stripe-2/node_modules/@prisma/client/runtime/index.js:27839
          throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);
                ^
Error: The provided database string is invalid. Error parsing connection string: invalid port number in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
    at startFn (/Users/swf/projects/remix-stripe-2/node_modules/@prisma/client/runtime/index.js:27839:17)
```

I wonder if something in .env was expected to be changed because mine still says `DATABASE_URL="postgresql://USER:PASSWORD@HOST:PORT/DATABASE"`

## Steps to reproduce

```bash
npx create-remix@latest --template dev-xo/stripe-stack # select postgres and create at ./new-stripe-stack
cd new-stripe-stack
npm run dev # load localhost:3000 and see error above
rm -rf node_modules && npm install 
npm run dev # load localhost and see second error above
```

**Comment by dev-xo** [comment]
Hello @sfirrin can you contact me directly thru Discord?
I'm in the Remix Discord as dev-xo#9732

Gonna look into it right now.

**Comment by dev-xo** [comment]
Have you set the database into the `.env` file?
If I'm not wrong, you need to replace `DATABASE_URL="postgresql://USER:PASSWORD@HOST:PORT/DATABASE"` with your own Postgres database credentials.

**Comment by sfirrin** [comment]
Ah thanks a lot for your help @dev-xo. I didn't realize that I needed to get the postgres process running and add the URL to .env. I've done that now and the dev server is up and running.

**Comment by dev-xo** [comment]
Happy to help @sfirrin!

If you got any other issue / request, feel free to ask!
