### ISSUE TITLE
Subscribe user to Free Stripe Plan after they register for a new account.

### ISSUE THREAD

**Issue by cmarabate** [dev-xo/stripe-stack#57]
Hello, I love this starter but there is one thing I would like to know how to change.

Instead of first plan being a paid plan, I want to make the first plan a free plan and have it automatically subscribe them to that plan after they register a new account. This way they will show up in my Stripe Dashboard as customers even if you do not subscribe to a paid plan. That way I can collect the email address of all my users in Stripe.

![image](https://user-images.githubusercontent.com/12236062/215892639-70efbf6a-ae76-4ef3-b778-7613b8de1dd6.png)

Then when they first view the select your plan page it would say something like "Current Membership" instead of "Subscribe to Free Membership"

The above would be ideal but I would also accept a solution that just lets me add an additional free plan that doesn't show up on the "Select your plan" but it would automatically subscribe them to this plan when they register. 

Thanks,

Chris

**Comment by dev-xo** [comment]
Hello @cmarabate ! First of all thank you for reaching on here.
Could you please add me on discord? I think I could help you directly from direct messages.
I'm dev-xo#9732 in the Remix Discord.

So If I understand you correctly, you wanna create a Customer with a Free Membership.
You could do that in the Create Account in the `/services/auth/config.server.ts`.

When you create a User you can also create a Customer via some Stripe API call like `create-customer`.
Also you could set an Initial plan to your user to the Free Tier, when you are creating it.

Not sure if this was your question, in any case, feel free to contact me directly.

**Comment by dev-xo** [comment]
Im gonna update the template this next few days.
I could have created the user and the customer at the same time.

But in post of keeping things a bit cleaner, I preferred to create the customer, only when the user it's about to Subscribe.
But that's only a preference.

You have 2 options:
- Create the user and the Customer at the same time, calling Stripe API.
- Create the user and set a Free Plan tier by default, but not calling Stripe API (not creating the Customer)

Both ways are good. I think I could update the template, to the second one by default.

**Comment by cmarabate** [comment]
Yes that is exactly what I want. Thanks a bunch!

**Comment by dev-xo** [comment]
Feel free to reach me directly on Discord in case you need some help with the implementation.

The template will be updated this next few days.
Gonna simplify a few things.

Have fun and feel free to ask any other thing!
